version: "3.8"

services:
  api:
    image: ${AWS_ECR}/danji-api:latest
    container_name: danji-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env.api
    depends_on:
      - postgres
      - valkey

  chat:
    image: ${AWS_ECR}/danji-chat:latest
    container_name: danji-chat
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.chat
    depends_on:
      - mongo
      - valkey

  postgres:
    image: postgres:15
    container_name: danji-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_POSTGRES}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    container_name: danji-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${DB_MONGO}
    volumes:
      - ${MONGO_DATA}:/data/db
    ports:
      - "27017:27017"

  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: danji-valkey
    restart: unless-stopped
    volumes:
      - ${VALKEY_DATA}:/data/db
    ports:
      - "6379:6379"