version: "3.8"

services:
  api:
    image: mingdodev/danji-api:latest
    container_name: danji-api
    ports:
      - "8080:8080"
    restart: unless-stopped


    environment:
      - SPRING_PROFILES_ACTIVE=prod

  chat:
    image: mingdodev/danji-chat:latest
    container_name: danji-chat
    ports:
      - "3000:3000"
    restart: unless-stopped
