services:
  api:
    image: 966917020469.dkr.ecr.ap-northeast-2.amazonaws.com/danji-api:latest
    container_name: danji-api
    platform: linux/amd64
    ports:
      - "8080:8080"
    entrypoint: sh -c "java $$JAVA_OPTS -jar /app.jar"
    environment:
      JAVA_OPTS: -XX:NativeMemoryTracking=summary
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env.dev
    depends_on:
      - postgres
      - valkey

  chat:
    image: 966917020469.dkr.ecr.ap-northeast-2.amazonaws.com/danji-chat:latest
    container_name: danji-chat
    platform: linux/amd64
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - mongo
      - valkey

  postgres:
    image: postgres:15
    container_name: danji-postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_DB: danji
      POSTGRES_USER: danji
      POSTGRES_PASSWORD: danji
    volumes:
      - ./data/docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4.18
    container_name: danji-mongo
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: danji
    volumes:
      - ./data/docker/mongo:/data/db
    ports:
      - "27017:27017"

  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: danji-valkey
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./data/docker/redis:/data
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: danji-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: danji-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    container_name: danji-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - chat