spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      port: 6379

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    url: /api/v3/api-docs

aws:
  region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
  cloudfront:
    domain: ${AWS_CLOUDFRONT}

jwt:
  secret: ${JWT_SECRET_KEY}